"""add status column to interviewpreps

Revision ID: 18c3288622a5
Revises: 3446f6ffd539
Create Date: 2026-02-04 20:25:02.850336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18c3288622a5'
down_revision: Union[str, Sequence[str], None] = '3446f6ffd539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignment_questions_assignment_id_fkey'), 'assignment_questions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_questions', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.add_column('interviewpreps', sa.Column('status', sa.Enum('GENERATING', 'READY', 'SUBMITTED', name='interviewprepstatus'), nullable=True))
    op.alter_column('interviewpreps', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_unique_constraint('_user_industry_uc', 'student_insights', ['user_id', 'industry'])
    op.drop_constraint(op.f('submissions_assignment_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_assignment_id_fkey'), 'submissions', 'assignments', ['assignment_id'], ['id'])
    op.drop_constraint('_user_industry_uc', 'student_insights', type_='unique')
    op.alter_column('interviewpreps', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('interviewpreps', 'status')
    op.drop_constraint(None, 'assignment_questions', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_questions_assignment_id_fkey'), 'assignment_questions', 'assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###
