from .v1.endpoints import ai_evaluator
from .v1.endpoints import assignment
from .v1.endpoints import auth
from .v1.endpoints import docsupload
from .v1.endpoints import generate_assignment
from .v1.endpoints import generate_notes
from .v1.endpoints import group
from .v1.endpoints import groupMessage
from .v1.endpoints import inngest_route
from .v1.endpoints import interviewPerp
from .v1.endpoints import notes
from .v1.endpoints import studentInsight
from .v1.endpoints import submission
from .v1.endpoints import subscription
from .v1.endpoints import teacherInsight
